on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: R-CMD-check

env:
  BROKERS_INTERNAL: localhost:9092
  BROKERS: localhost:9093
  TOPIC: test-topic

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
#          - {os: macos-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - name: Install mac dependency
        if: runner.os == 'macos'
        run: |
          brew install librdkafka docker docker-compose
          colima start

      - name: Install linux dependency
        if: runner.os == 'linux'
        run: |
          sudo apt install librdkafka-dev docker-compose

      - name: Start kafka cluster
        run: |
          docker-compose up -d

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Create and populate .Renviron file
        run: |
          echo TOPIC="$TOPIC" > ~/.Renviron
          echo BROKERS="$BROKERS" >> ~/.Renviron

      - name: Configure kafka server for tests
        run: |
          docker exec kafka-server \
            /opt/bitnami/kafka/bin/kafka-topics.sh \
              --bootstrap-server $BROKERS_INTERNAL \
              --create --topic $TOPIC \
              --partitions 4

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
